### ISSUE TITLE
Enhancing action space

### ISSUE THREAD

**Issue by pthangeda** [FiMDP/FiMDPEnv#5]
The action space currently consists of the weak and strong versions of N, S, W, and E actions. A natural enhancement would be to include diagonal actions, NW, NE, SW, SE, in both strong and weak forms. This would increase the action space to sixteen actions. I anticipate minimal to no changes to the existing interface to support this addition.

**Comment by xblahoud** [comment]
Let me suggest something. Instead of having implicit actions denoted by integers, we can provide a list of actions, where each action is a tuple of the following form (or similar).
```
(label, Weak/Strong, effect_x, effect_y)
```
This could simplify the code and get rid of the if statements at https://github.com/pthangeda/FiMDPEnv/blob/master/fimdpenv/UUVEnv.py#L80

We can also provide two default lists: 4 & 8 directions.

**Comment by pthangeda** [comment]
This issue has been addressed in 6a8672ab65d69333199e4b0018b2055f0c3d7e64, although not with the new labeling schema. The current enhancement builds upon existing framework. I am leaving the issue open as I intend to make more internal changes keeping the suggestion in mind.
